paths:
  /api/products:
    get:
      summary: Returns a list with all the products in store.
      responses:
        '200':
          description: A JSON array of objects containing each product information.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/products'
        '500':
          description: Error while getting products from database